# Contract Addresses
pools:
  - address: "0000000000000000000000000000000000001017" # ETHST-USDST pool
  - address: "0000000000000000000000000000000000001019" # WBTCST-USDST pool
  - address: "000000000000000000000000000000000000101b" # GOLDST-USDST pool
  - address: "000000000000000000000000000000000000101d" # SILVST-USDST pool
  - address: "cb85e12ca5d98de95715fc75ae251a66b662ea06" # GOLDST-SILVST pool
  - address: "34d7caf576cf9493f054d9eced99dcd463eba4b7" # ETHST-BTCST pool
  - address: "72f029994b1003447b4fcae5025ae78fcbec258e" # wstETHST-USDST pool
# Trading Parameters
trading:
  fee_bps: 30 # Pool fee in basis points (0.3%)
  min_profit: 0.01 # $0.01 minimum profit

# Oracle Configuration
oracle:
  timeout: 10 # API request timeout in seconds
  blockapps_price_oracle: "0000000000000000000000000000000000001002" # BlockApps on-chain price oracle address

# Execution Settings
execution:
  execution_interval: 60 # seconds between scans
  # vault_addr: "d556695364551c8c7eb336f0bed9aed9e1acd69d" # this is testnet vault address
